package com.ddzj.repository;

import com.ddzj.entity.TblUserRole;

public interface TblUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated Sat Nov 10 19:31:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated Sat Nov 10 19:31:33 CST 2018
     */
    int insert(TblUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated Sat Nov 10 19:31:33 CST 2018
     */
    int insertSelective(TblUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated Sat Nov 10 19:31:33 CST 2018
     */
    TblUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated Sat Nov 10 19:31:33 CST 2018
     */
    int updateByPrimaryKeySelective(TblUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated Sat Nov 10 19:31:33 CST 2018
     */
    int updateByPrimaryKey(TblUserRole record);
}